title: Your awesome title
email: your-email@domain.com
description: Desatascos Inca realiza el proceso de limpieza de las tuberías de manera regular, así evitarás que los atascos se produzcan constantemente y con mayor gravedad, dificultando la solución rápida. Somos los profesionales en desatascos de Mallorca.

baseurl: "/"
url: http://keralahost.in/aliciapereira
google_adsense: Your-adsense-code

markdown: kramdown

name: Your awesome title

date: 2019-05-04 04:16:27 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/aliciapereira/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: aliciapereira
